import Link from 'next/link';

export default function TermsPage() {
  return (
    <div className="container mx-auto px-4 py-16 max-w-4xl">
      <div className="text-center mb-12">
        <h1 className="text-3xl font-bold text-gray-900 mb-4">Terms & Conditions</h1>
        <p className="text-gray-600">Last updated: 01/09/2025</p>
      </div>
      
      <div className="prose max-w-none">
        <p className="text-gray-700 mb-6">
        Welcome to MetaMed (“the Application”, “the App”, “we”, “our”, or “us”). These Terms and Conditions (“Terms”) govern your use of the MetaMed application and any related website or services. By accessing or using the App, you agree to these Terms. If you do not agree, you must not use the App.
        </p>
        
        <h2 className="text-xl font-semibold mt-8 mb-4">1. Purpose of the Application</h2>
        <p className="text-gray-700 mb-4">
        MetaMed is a clinical decision support tool designed for use by healthcare professionals for educational purposes.
The App is designed to allow secure communication and information transmission between healthcare workers and patients.
The App is not intended as a substitute for professional medical advice, diagnosis, or treatment.
        </p>
        
        <h2 className="text-xl font-semibold mt-8 mb-4">2. Eligibility</h2>
        <p className="text-gray-700 mb-4">
        You must be a licensed healthcare professional or an authorized clinical researcher to use the App in a medical decision-making context.
        By using the App, you confirm that you meet these requirements
        </p>
        
        <h2 className="text-xl font-semibold mt-8 mb-4">3. Medical Disclaimer</h2>
        <p className="text-gray-700 mb-4">
        The App provides decision support only and does not replace clinical judgment.
All outputs should be interpreted by a healthcare professional in the context of individual patient care.
We do not guarantee that recommendations will be complete, accurate, or up to date with every clinical guideline.
Patients must always seek medical advice directly from their healthcare provider.
        </p>
        
        <h2 className="text-xl font-semibold mt-8 mb-4">4. User Responsibilities</h2>
        <p className="text-gray-700 mb-4">
        You agree to enter only accurate, validated clinical data. You are responsible for verifying outputs before applying them in clinical practice.
You agree not to misuse the App for non-clinical, harmful, or unlawful purposes.
        </p>
        
        <h2 className="text-xl font-semibold mt-8 mb-4">5. Data Privacy</h2>
        <p className="text-gray-700 mb-4">
        
We respect your privacy and comply with GDPR and other applicable data protection laws.
Clinical data entered is not shared with third parties except as required by law.
        </p>
        
        <h2 className="text-xl font-semibold mt-8 mb-4">6. License and Restrictions</h2>
        <p className="text-gray-700 mb-4">
        We grant you a limited, non-transferable, revocable license to use the App for professional purposes.
You may not:
Reverse-engineer, copy, or distribute the App.
Use the App for patient self-diagnosis.
Misrepresent outputs as independent medical advice.
        </p>
        
        <h2 className="text-xl font-semibold mt-8 mb-4">7. Intellectual Property</h2>
        <p className="text-gray-700 mb-4">
        TAll intellectual property in MetaMed, including algorithms, logic models, and trademarks, belongs to Metamed.
Unauthorized use of the App’s content, branding, or technology is prohibited.

        </p>
        
        <h2 className="text-xl font-semibold mt-8 mb-4">8. Limitation of Liability</h2>
        <p className="text-gray-700 mb-4">
        To the fullest extent permitted by law, we disclaim liability for:
Any reliance on outputs generated by the App.
Indirect, incidental, or consequential damages.The App is provided “as is” without warranties of any kind.
        </p>
        
        <h2 className="text-xl font-semibold mt-8 mb-4">9. Termination</h2>
        <p className="text-gray-700 mb-4">
        We may suspend or terminate access if you violate these Terms.
You may stop using the App at any time.
        </p>
        
        <h2 className="text-xl font-semibold mt-8 mb-4">10. Governing Law</h2>
        <p className="text-gray-700 mb-4">
        These Terms are governed by the laws of Ireland
Any disputes shall be subject to the exclusive jurisdiction of the Irish courts.
        </p>
        
        <h2 className="text-xl font-semibold mt-8 mb-4">11. Modifications</h2>
        <p className="text-gray-700 mb-4">
        We may update these Terms from time to time. We will notify you of any changes by posting the new Terms on this page.
        </p>
        
        <h2 className="text-xl font-semibold mt-8 mb-4">12. Contact Us</h2>
        <p className="text-gray-700 mb-4">
        If you have any questions about these Terms, please contact us at{' '}
        <a href="mailto:info@metamed.com" className="text-blue-600 hover:underline">info@metamed.com</a>.
        26 Upper Pembroke St, Dublin 2
        </p>
      </div>
      
      <div className="mt-12 pt-6 border-t border-gray-200 text-center">
        <Link 
          href="/" 
          className="text-blue-600 hover:underline"
        >
          &larr; Back to Home
        </Link>
      </div>
    </div>
  );
}
