"use client"

import { useState } from "react"
import { motion, AnimatePresence } from "framer-motion"
import { X, Copy, Check, Printer, AlertTriangle, AlertCircle, ChevronDown, ChevronUp, FileText } from "lucide-react"
import { cn } from "@/lib/utils"
import { GenerateResponse } from "./types"

interface NoteViewerProps {
  result: GenerateResponse
  onClose: () => void
}

export function NoteViewer({ result, onClose }: NoteViewerProps) {
  const [copied, setCopied] = useState(false)
  const [expandedSections, setExpandedSections] = useState<Set<string>>(new Set())

  const handleCopy = () => {
    navigator.clipboard.writeText(result.generated_note).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    })
  }

  const handlePrint = () => {
    const win = window.open("", "_blank")
    if (!win) return
    win.document.write(`
      <html>
        <head>
          <title>${result.output_type} — ${result.note_type}</title>
          <style>
            @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800&display=swap');
            body { 
              font-family: 'Inter', -apple-system, sans-serif; 
              max-width: 800px; 
              margin: 40px auto; 
              color: #0f172a; 
              line-height: 1.6;
              padding: 0 40px;
            }
            .header {
              border-bottom: 2px solid #e11d48;
              padding-bottom: 20px;
              margin-bottom: 30px;
              display: flex;
              justify-content: space-between;
              align-items: flex-end;
            }
            .header-info h1 {
              color: #e11d48;
              margin: 0;
              font-size: 24px;
              font-weight: 800;
              text-transform: uppercase;
              letter-spacing: -0.025em;
            }
            .header-info p {
              margin: 5px 0 0 0;
              font-size: 12px;
              font-weight: 700;
              color: #64748b;
              text-transform: uppercase;
              letter-spacing: 0.1em;
            }
            .date {
              font-size: 12px;
              color: #94a3b8;
              font-weight: 600;
            }
            .content {
              font-size: 14px;
              white-space: pre-wrap;
            }
            .section-title {
              font-size: 11px;
              font-weight: 800;
              text-transform: uppercase;
              letter-spacing: 0.05em;
              color: #e11d48;
              margin-top: 30px;
              margin-bottom: 10px;
              border-bottom: 1px solid #f1f5f9;
              padding-bottom: 4px;
            }
            .disclaimer { 
              background: #f8fafc; 
              border: 1px solid #e2e8f0; 
              padding: 16px; 
              border-radius: 8px; 
              color: #64748b; 
              font-size: 11px; 
              margin-top: 50px;
              font-style: italic;
            }
            .warning { 
              background: #fffbeb; 
              border-left: 4px solid #f59e0b; 
              padding: 12px 16px; 
              color: #92400e; 
              font-size: 12px; 
              margin: 16px 0;
              font-weight: 600;
            }
            @media print {
              body { margin: 20px auto; }
              .header { border-bottom-color: #000; }
              .header-info h1 { color: #000; }
              .section-title { color: #000; border-bottom-color: #eee; }
            }
          </style>
        </head>
        <body>
          <div class="header">
            <div class="header-info">
              <h1>${result.output_type.replace(/_/g, " ")}</h1>
              <p>${result.note_type}</p>
            </div>
            <div class="date">Issued: ${new Date().toLocaleDateString()}</div>
          </div>
          
          ${result.warnings.map(w => `<div class="warning">⚠️ ATTENTION: ${w}</div>`).join("")}
          
          <div class="content">${result.generated_note}</div>
          
          <div class="disclaimer">
            <strong>Medical Disclaimer:</strong> ${result.disclaimer}
            <br><br>
            <small>This document was generated by AI assistance. Please review and verify all clinical information.</small>
          </div>
        </body>
      </html>
    `)
    win.document.close()
    win.print()
  }

  const toggleSection = (key: string) => {
    setExpandedSections((prev) => {
      const next = new Set(prev)
      if (next.has(key)) next.delete(key)
      else next.add(key)
      return next
    })
  }

  const outputLabel =
    result.output_type === "CLINICAL_NOTE"
      ? "📄 Clinical Note"
      : result.output_type === "HANDOVER_NOTE"
      ? "🔄 Handover Note"
      : "📧 Discharge Letter"

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-md flex items-center justify-center p-4 lg:p-8"
      onClick={(e) => e.target === e.currentTarget && onClose()}
    >
      <motion.div
        initial={{ scale: 0.98, opacity: 0, y: 10 }}
        animate={{ scale: 1, opacity: 1, y: 0 }}
        exit={{ scale: 0.98, opacity: 0, y: 10 }}
        className="bg-white rounded-3xl shadow-2xl w-full max-w-5xl max-h-full flex flex-col overflow-hidden border border-slate-200"
      >
        {/* Header bar */}
        <div className="flex items-center justify-between px-8 py-5 border-b border-slate-100 bg-white shrink-0">
          <div className="flex items-center gap-4">
            <div className="w-10 h-10 rounded-2xl bg-rose-500 flex items-center justify-center shadow-lg shadow-rose-500/20">
              <FileText className="w-5 h-5 text-white" />
            </div>
            <div>
              <h2 className="font-extrabold text-slate-900 text-xl tracking-tight leading-none">
                {outputLabel}
              </h2>
              <p className="text-[10px] font-bold text-slate-400 mt-1.5 uppercase tracking-widest flex items-center gap-2">
                <span className="w-1.5 h-1.5 rounded-full bg-emerald-500" />
                {result.note_type} • Professional Record
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center gap-2 px-4 py-2.5 rounded-xl border border-slate-200 text-xs font-bold text-slate-600 hover:border-rose-300 hover:text-rose-600 hover:bg-rose-50 transition-all active:scale-95"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
              {copied ? "Copied" : "Copy Content"}
            </button>
            <button
              onClick={handlePrint}
              className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-slate-900 text-white text-xs font-bold hover:bg-slate-800 transition-all active:scale-95 shadow-lg shadow-slate-900/20"
            >
              <Printer className="w-3.5 h-3.5" />
              Print Report
            </button>
            <div className="w-px h-6 bg-slate-100 mx-2" />
            <button
              onClick={onClose}
              className="p-2.5 rounded-xl text-slate-400 hover:text-rose-600 hover:bg-rose-50 transition-all active:scale-90"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Report Preview */}
        <div className="flex-1 overflow-y-auto bg-slate-50/50 p-8 lg:p-12">
          <div className="max-w-3xl mx-auto space-y-8">
            {/* Warnings Alert */}
            {result.warnings.length > 0 && (
              <div className="space-y-3">
                {result.warnings.map((w, i) => (
                  <div key={i} className="flex items-start gap-4 bg-amber-50/80 border border-amber-200/60 rounded-2xl px-5 py-4 backdrop-blur-sm">
                    <div className="w-8 h-8 rounded-xl bg-amber-100 flex items-center justify-center shrink-0">
                      <AlertTriangle className="w-4 h-4 text-amber-600" />
                    </div>
                    <div>
                      <h4 className="text-[10px] font-black text-amber-900 uppercase tracking-widest mb-1">Attention Required</h4>
                      <p className="text-xs font-bold text-amber-800/80 leading-relaxed">{w}</p>
                    </div>
                  </div>
                ))}
              </div>
            )}

            {/* The Document Paper */}
            <div className="bg-white rounded-[2.5rem] shadow-sm border border-slate-100 overflow-hidden relative min-h-[600px] flex flex-col">
              {/* Report Header Design */}
              <div className="p-10 pb-0 flex justify-between items-start">
                <div className="space-y-2">
                    <div className="text-[10px] font-black text-rose-500 uppercase tracking-[0.2em] mb-4">Official Clinical Record</div>
                    <h1 className="text-3xl font-black text-slate-900 tracking-tighter">
                        {result.output_type.replace(/_/g, " ")}
                    </h1>
                    <p className="text-sm font-medium text-slate-500">{result.note_type}</p>
                </div>
                <div className="text-right">
                    <div className="text-[11px] font-bold text-slate-400 uppercase tracking-widest">Date Issued</div>
                    <div className="text-sm font-black text-slate-900">{new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}</div>
                </div>
              </div>

              {/* Watermark/Texture */}
              <div className="absolute top-0 right-0 p-10 opacity-[0.03] pointer-events-none">
                 <FileText className="w-64 h-64 -rotate-12" />
              </div>

              {/* Document Content */}
              <div className="p-10 pt-12 flex-1">
                {/* Visual Sections (Accordion) */}
                {Object.keys(result.sections).length > 0 && (
                    <div className="space-y-4 mb-12">
                        <div className="flex items-center gap-3 mb-6">
                            <span className="h-px flex-1 bg-slate-100" />
                            <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest whitespace-nowrap">Structured View</span>
                            <span className="h-px flex-1 bg-slate-100" />
                        </div>
                        {Object.entries(result.sections).map(([title, content]) => {
                            const isOpen = expandedSections.has(title)
                            return (
                                <div key={title} className={cn(
                                    "rounded-2xl border transition-all duration-300",
                                    isOpen ? "border-rose-100 bg-rose-50/30 ring-4 ring-rose-500/5 shadow-sm" : "border-slate-100 bg-white hover:border-slate-200"
                                )}>
                                    <button
                                        onClick={() => toggleSection(title)}
                                        className="w-full flex items-center justify-between px-5 py-4 text-left"
                                    >
                                        <div className="flex items-center gap-3">
                                            <div className={cn(
                                                "w-1.5 h-1.5 rounded-full transition-colors",
                                                isOpen ? "bg-rose-500" : "bg-slate-300"
                                            )} />
                                            <span className={cn(
                                                "text-[11px] font-black uppercase tracking-wider",
                                                isOpen ? "text-rose-950" : "text-slate-600"
                                            )}>
                                                {title}
                                            </span>
                                        </div>
                                        {isOpen ? (
                                            <ChevronUp className="w-4 h-4 text-rose-400" />
                                        ) : (
                                            <ChevronDown className="w-4 h-4 text-slate-300" />
                                        )}
                                    </button>
                                    <AnimatePresence>
                                        {isOpen && (
                                            <motion.div
                                                initial={{ height: 0, opacity: 0 }}
                                                animate={{ height: "auto", opacity: 1 }}
                                                exit={{ height: 0, opacity: 0 }}
                                                transition={{ duration: 0.3, ease: "easeInOut" }}
                                                className="overflow-hidden"
                                            >
                                                <div className="px-6 pb-5 pt-0 text-[13px] text-slate-700 leading-relaxed whitespace-pre-wrap font-medium">
                                                    {content}
                                                </div>
                                            </motion.div>
                                        )}
                                    </AnimatePresence>
                                </div>
                            )
                        })}
                    </div>
                )}

                {/* Primary Report Content */}
                <div className="space-y-4">
                    <div className="flex items-center gap-3 mb-6">
                        <span className="h-px flex-1 bg-slate-100" />
                        <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest whitespace-nowrap">Full Interpretation</span>
                        <span className="h-px flex-1 bg-slate-100" />
                    </div>
                    <div className="text-[14px] text-slate-800 leading-[1.8] font-medium whitespace-pre-wrap bg-slate-50/50 rounded-3xl p-8 border border-slate-100/50">
                        {result.generated_note}
                    </div>
                </div>
              </div>

              {/* Footer / Disclaimer */}
              <div className="p-10 bg-slate-50 border-t border-slate-100">
                <div className="flex items-start gap-4">
                    <div className="w-10 h-10 rounded-xl bg-red-100 flex items-center justify-center shrink-0">
                        <AlertCircle className="w-5 h-5 text-red-600" />
                    </div>
                    <div>
                        <h4 className="text-[11px] font-black text-red-900 uppercase tracking-widest mb-1.5 flex items-center gap-2">
                            Clinical Disclaimer
                            <span className="w-1.5 h-1.5 rounded-full bg-red-500 animate-pulse" />
                        </h4>
                        <p className="text-[12px] text-red-800/70 leading-relaxed font-bold italic">
                            {result.disclaimer}
                        </p>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </motion.div>
    </motion.div>
  )
}
