'use client';

import { useState, useRef } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { motion, AnimatePresence } from 'framer-motion';
import { Shield, AlertTriangle, CheckCircle2, ChevronDown, ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import Image from 'next/image';

const disclaimerSections = [
    {
        number: '1',
        title: 'General Informational Purpose',
        content: `The information, analyses, summaries, outputs, communication tools, and other materials provided through this website and associated digital services (collectively referred to as the "Platform") are provided solely for informational, educational, and organisational purposes.

The Platform is designed to facilitate structured communication and information exchange between users, including healthcare professionals and patients, and to assist with the organisation and presentation of health-related information.

Nothing contained within the Platform should be interpreted as providing medical advice, diagnosis, treatment recommendations, or professional medical services.

Any information or outputs generated through the Platform represent general informational content, analytical interpretation, or opinion-based summaries derived from available inputs and references.

Such outputs must not be relied upon as a substitute for professional medical judgment or clinical assessment.`,
    },
    {
        number: '2',
        title: 'Clinical Judgment and Professional Oversight',
        content: `All outputs generated by the Platform are intended solely to support healthcare communication, documentation, and workflow efficiency.

Any summaries, interpretations, automated analyses, or suggested outputs must be independently reviewed, verified, and interpreted by a qualified healthcare professional prior to any clinical application.

Clinical decisions must always be made by the licensed healthcare professional responsible for the patient's care, who must consider the full clinical context including: medical history, physical examination findings, diagnostic test results, comorbid conditions, medication use, patient preferences, and evolving clinical circumstances.

Under no circumstances should the Platform be used as the sole basis for diagnosis, treatment decisions, or clinical intervention.`,
    },
    {
        number: '3',
        title: 'Individual Clinical Circumstances',
        content: `Healthcare decisions depend on individual patient characteristics and complex clinical variables that cannot be fully captured through automated systems.

Outputs generated by the Platform may therefore not reflect the full clinical context of a specific patient.

Users must recognise that general informational outputs may not be applicable to individual patients, and all results must be interpreted within the broader clinical framework by a qualified healthcare professional.`,
    },
    {
        number: '4',
        title: 'Accuracy, Completeness, and Data Integrity',
        content: `The Platform may rely on: user-entered information, automated processing systems, algorithmic models, external reference sources, and statistical or computational analysis.

While reasonable efforts are made to ensure that the Platform operates in accordance with recognised standards and reliable sources, no guarantee or warranty is provided regarding the accuracy, completeness, reliability, or timeliness of any information or outputs generated.

Errors, omissions, or misinterpretations may occur.

Users remain responsible for ensuring that: data entered into the Platform is accurate and complete, outputs are independently validated, and professional clinical judgment is applied before any decisions are made.`,
    },
    {
        number: '5',
        title: 'Clinical Decision Support Disclaimer (EU MDR Alignment)',
        content: `The Platform is intended to function as an informational support and communication tool designed to assist with the organisation, summarisation, and presentation of healthcare-related information.

The Platform does not independently diagnose disease, determine treatment, or replace clinical decision-making by a qualified healthcare professional.

Any guideline-based references, structured calculations, or automated outputs provided by the Platform are intended solely to support professional interpretation.

Final clinical decisions must always be made by the treating healthcare professional, who retains full responsibility for patient management and outcomes.`,
    },
    {
        number: '6',
        title: 'Artificial Intelligence and Algorithmic Output Disclaimer',
        content: `Certain components of the Platform may utilise automated processing, algorithmic systems, statistical models, or artificial intelligence technologies to assist in generating informational summaries or analytical outputs.

These systems may analyse patterns within available data in order to produce outputs designed to assist users in reviewing or organising information.

However: algorithmic outputs may contain inaccuracies or incomplete interpretations, automated systems cannot account for all clinical variables, and artificial intelligence systems do not possess clinical judgment.

All AI-generated or algorithmically derived outputs must therefore be reviewed and validated by a qualified healthcare professional before any clinical use.`,
    },
    {
        number: '7',
        title: 'No Physician–Patient Relationship',
        content: `Use of the Platform does not establish a physician–patient relationship between users and the developers, operators, or contributors associated with the Platform.

Healthcare professionals using the Platform remain solely responsible for the clinical care of their patients.

Patients should seek medical advice directly from their own licensed healthcare provider for any medical concerns.`,
    },
    {
        number: '8',
        title: 'Not Intended for Emergency Use',
        content: `The Platform is not designed for use in emergency or urgent medical situations.

Users who believe they or another individual may be experiencing a medical emergency should immediately contact emergency services or seek urgent medical attention.

The Platform should not be relied upon for time-sensitive or emergency decision-making.`,
    },
    {
        number: '9',
        title: 'Limitation of Liability',
        content: `To the fullest extent permitted by applicable law, the developers, operators, affiliates, contributors, and associated parties of the Platform accept no liability for any direct, indirect, incidental, or consequential damages arising from: use of the Platform, reliance on outputs or information generated by the Platform, errors, omissions, or inaccuracies, interruptions, delays, or technical failures, or clinical decisions made by users or third parties.

Use of the Platform is undertaken entirely at the user's own risk.`,
    },
    {
        number: '10',
        title: 'User Responsibilities',
        content: `By accessing or using the Platform, users acknowledge and agree that: the Platform provides informational and organisational support only, all outputs require independent professional verification, clinical responsibility remains solely with the treating healthcare professional, and the Platform is not a substitute for professional clinical judgment.`,
    },
    {
        number: '11',
        title: 'Patient Safety Statement',
        content: `For patient users, the Platform is designed to support communication and information exchange with healthcare providers.

Information presented through the Platform should not be used to independently diagnose or treat medical conditions.

Patients should always consult their own healthcare professional regarding symptoms, diagnoses, or treatment options.`,
    },
    {
        number: '12',
        title: 'Terms of Use Acknowledgement',
        content: `Access to and use of the Platform constitutes acceptance of the Platform's Terms of Use, Privacy Policy, and all associated policies governing the operation of the service.

Users agree to use the Platform in accordance with applicable laws, ethical standards, and professional guidelines.

Users are responsible for ensuring that their use of the Platform complies with relevant data protection, clinical governance, and professional regulatory requirements.`,
    },
    {
        number: '13',
        title: 'Clinical Safety and Governance Statement',
        content: `The Platform has been designed with consideration for clinical governance principles, patient safety, and responsible technology use.

Where applicable, safeguards may include: professional review of outputs, structured clinical workflows, transparency regarding automated processes, and secure data infrastructure.

Nevertheless, the Platform remains a supportive information tool, and responsibility for safe clinical practice remains with the healthcare professionals using the system.`,
    },
    {
        number: '14',
        title: 'Artificial Intelligence Transparency Statement',
        content: `Where artificial intelligence or algorithmic systems are used within the Platform, these technologies are intended to support the organisation and interpretation of information rather than to replace professional clinical judgment.

AI-generated outputs are probabilistic in nature and may reflect limitations inherent to: training data, algorithm design, incomplete or inaccurate input data, and evolving medical knowledge.

Users must therefore treat such outputs as supportive informational content rather than definitive clinical determinations.`,
    },
    {
        number: '15',
        title: 'Regulatory Status',
        content: `Unless otherwise explicitly stated, the Platform should be understood as an informational and communication support system.

It should not be interpreted as a certified medical device or diagnostic system unless and until formal regulatory certification has been obtained under applicable regulatory frameworks.`,
    },
    {
        number: '16',
        title: 'Updates to This Disclaimer',
        content: `This disclaimer may be updated periodically to reflect changes in the Platform, regulatory guidance, legal requirements, or operational practices.

Continued use of the Platform constitutes acceptance of the most recent version of this disclaimer.`,
    },
];

export default function DisclaimerPage() {
    const router = useRouter();
    const searchParams = useSearchParams();
    const [hasScrolledToBottom, setHasScrolledToBottom] = useState(false);
    const [acknowledged, setAcknowledged] = useState(false);
    const [isProceeding, setIsProceeding] = useState(false);
    const [expandedSection, setExpandedSection] = useState<string | null>('1');
    const scrollRef = useRef<HTMLDivElement>(null);

    const handleScroll = () => {
        const el = scrollRef.current;
        if (!el) return;
        const distanceFromBottom = el.scrollHeight - el.scrollTop - el.clientHeight;
        if (distanceFromBottom < 50) {
            setHasScrolledToBottom(true);
        }
    };

    const handleProceed = () => {
        if (!acknowledged) return;
        setIsProceeding(true);

        // Read destination from URL query param — no localStorage needed
        const redirect = searchParams.get('redirect') || '/patient/chat';
        setTimeout(() => router.push(redirect), 300);
    };

    return (
        <div className="min-h-screen bg-gradient-to-br from-slate-50 via-rose-50/20 to-white font-sans selection:bg-rose-100 selection:text-rose-900">
            {/* Header */}
            <div className="sticky top-0 z-50 bg-white/90 backdrop-blur-md border-b border-rose-100 shadow-sm">
                <div className="container mx-auto px-6 py-4 flex items-center justify-between">
                    <div className="flex items-center gap-3">
                        <div className="relative w-9 h-9">
                            <Image src="/MetamedMDlogo (2).png" alt="MetaMedMD Logo" fill className="object-contain" priority />
                        </div>
                        <div className="flex flex-col">
                            <span className="font-bold text-base leading-none text-rose-950">CLARA™</span>
                            <span className="text-[9px] leading-none text-rose-500 font-black tracking-[0.15em] uppercase mt-0.5">by MetaMedMD</span>
                        </div>
                    </div>
                    <div className="flex items-center gap-2 px-4 py-1.5 bg-amber-50 border border-amber-200 rounded-full">
                        <AlertTriangle className="h-3.5 w-3.5 text-amber-500" />
                        <span className="text-xs font-bold text-amber-700 uppercase tracking-wider">Important Legal Notice</span>
                    </div>
                </div>
            </div>

            <div className="container mx-auto px-4 sm:px-6 py-10 max-w-4xl">
                {/* Hero */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6 }}
                    className="text-center mb-10"
                >
                    <div className="inline-flex items-center justify-center w-16 h-16 bg-rose-100 rounded-[20px] mb-6 mx-auto">
                        <Shield className="h-8 w-8 text-rose-500" />
                    </div>
                    <h1 className="text-3xl sm:text-4xl font-black text-slate-900 mb-4 tracking-tight">
                        Comprehensive Website, Clinical Support,<br />
                        <span className="text-rose-500">and AI Platform Disclaimer</span>
                    </h1>
                    <p className="text-base text-slate-500 font-medium max-w-2xl mx-auto leading-relaxed">
                        Please read this disclaimer carefully before using the CLARA platform. You must scroll through and acknowledge all sections to proceed.
                    </p>
                </motion.div>

                {/* Scrollable Content */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6, delay: 0.15 }}
                    className="bg-white rounded-[32px] border border-rose-100 shadow-[0_20px_60px_rgba(244,63,94,0.07)] overflow-hidden mb-6"
                >
                    <div
                        ref={scrollRef}
                        onScroll={handleScroll}
                        className="h-[480px] overflow-y-auto p-6 sm:p-8 custom-scrollbar"
                        style={{ scrollbarWidth: 'thin', scrollbarColor: '#fda4af transparent' }}
                    >
                        <div className="space-y-3">
                            {disclaimerSections.map((section, index) => (
                                <motion.div
                                    key={section.number}
                                    initial={{ opacity: 0, y: 8 }}
                                    animate={{ opacity: 1, y: 0 }}
                                    transition={{ delay: index * 0.02 }}
                                    className="border border-rose-100/80 rounded-2xl overflow-hidden"
                                >
                                    <button
                                        onClick={() =>
                                            setExpandedSection(
                                                expandedSection === section.number ? null : section.number
                                            )
                                        }
                                        className="w-full flex items-center justify-between p-4 sm:p-5 text-left hover:bg-rose-50/50 transition-colors group"
                                    >
                                        <div className="flex items-center gap-3">
                                            <span className="flex-shrink-0 w-7 h-7 bg-rose-500 text-white text-xs font-black rounded-lg flex items-center justify-center">
                                                {section.number}
                                            </span>
                                            <span className="font-bold text-slate-800 text-sm sm:text-base group-hover:text-rose-700 transition-colors leading-tight">
                                                {section.title}
                                            </span>
                                        </div>
                                        <ChevronDown
                                            className={`h-4 w-4 text-rose-400 flex-shrink-0 ml-3 transition-transform duration-300 ${expandedSection === section.number ? 'rotate-180' : ''
                                                }`}
                                        />
                                    </button>
                                    <AnimatePresence>
                                        {expandedSection === section.number && (
                                            <motion.div
                                                initial={{ height: 0, opacity: 0 }}
                                                animate={{ height: 'auto', opacity: 1 }}
                                                exit={{ height: 0, opacity: 0 }}
                                                transition={{ duration: 0.25, ease: 'easeInOut' }}
                                                className="overflow-hidden"
                                            >
                                                <div className="px-4 sm:px-5 pb-5 pt-1 bg-rose-50/20 border-t border-rose-100/60">
                                                    {section.content.split('\n\n').map((para, i) => (
                                                        <p key={i} className="text-sm text-slate-600 leading-relaxed font-medium mb-3 last:mb-0">
                                                            {para}
                                                        </p>
                                                    ))}
                                                </div>
                                            </motion.div>
                                        )}
                                    </AnimatePresence>
                                </motion.div>
                            ))}
                        </div>

                        {/* Bottom sentinel */}
                        <div className="h-4" />
                    </div>

                    {/* Scroll indicator */}
                    {!hasScrolledToBottom && (
                        <div className="flex items-center justify-center gap-2 py-3 bg-amber-50 border-t border-amber-100">
                            <ChevronDown className="h-4 w-4 text-amber-500 animate-bounce" />
                            <span className="text-xs font-bold text-amber-600 uppercase tracking-wider">Scroll to read all sections</span>
                            <ChevronDown className="h-4 w-4 text-amber-500 animate-bounce" />
                        </div>
                    )}
                    {hasScrolledToBottom && (
                        <div className="flex items-center justify-center gap-2 py-3 bg-green-50 border-t border-green-100">
                            <CheckCircle2 className="h-4 w-4 text-green-500" />
                            <span className="text-xs font-bold text-green-600 uppercase tracking-wider">You have read the full disclaimer</span>
                        </div>
                    )}
                </motion.div>

                {/* Acknowledgement */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6, delay: 0.25 }}
                    className="bg-white rounded-[28px] border border-rose-100 shadow-[0_10px_40px_rgba(244,63,94,0.05)] p-6 sm:p-8 mb-6"
                >
                    <div
                        onClick={() => hasScrolledToBottom && setAcknowledged(!acknowledged)}
                        className={`flex items-start gap-4 cursor-pointer group ${!hasScrolledToBottom ? 'opacity-50 cursor-not-allowed' : ''}`}
                    >
                        <div
                            className={`flex-shrink-0 w-6 h-6 rounded-lg border-2 flex items-center justify-center transition-all duration-200 mt-0.5 ${acknowledged
                                ? 'bg-rose-500 border-rose-500'
                                : hasScrolledToBottom
                                    ? 'border-rose-300 group-hover:border-rose-500'
                                    : 'border-slate-200'
                                }`}
                        >
                            {acknowledged && <CheckCircle2 className="h-4 w-4 text-white" />}
                        </div>
                        <div className="flex-1">
                            <p className="text-sm sm:text-base font-bold text-slate-800 leading-relaxed">
                                I have read, understood, and acknowledge the complete disclaimer above. I understand that the CLARA Platform is for informational and organisational purposes only, does not constitute medical advice, and that all clinical decisions remain my responsibility as a qualified healthcare professional or that I will consult a qualified professional.
                            </p>
                            {!hasScrolledToBottom && (
                                <p className="mt-2 text-xs text-amber-600 font-bold">
                                    ↑ Please scroll through all sections before acknowledging
                                </p>
                            )}
                        </div>
                    </div>
                </motion.div>

                {/* CTA Button */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6, delay: 0.35 }}
                    className="flex justify-center"
                >
                    <Button
                        onClick={handleProceed}
                        disabled={!acknowledged || isProceeding}
                        className={`h-14 px-12 text-base rounded-full font-black shadow-xl transition-all duration-300 flex items-center gap-3 ${acknowledged && !isProceeding
                            ? 'bg-rose-500 hover:bg-rose-600 text-white shadow-rose-500/25 hover:scale-105'
                            : 'bg-slate-200 text-slate-400 cursor-not-allowed shadow-none'
                            }`}
                    >
                        {isProceeding ? (
                            <>
                                <div className="h-4 w-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                                <span>Proceeding…</span>
                            </>
                        ) : (
                            <>
                                <span>I Acknowledge — Continue to Platform</span>
                                <ArrowRight className="h-5 w-5" />
                            </>
                        )}
                    </Button>
                </motion.div>

                <p className="text-center text-xs text-slate-400 font-medium mt-6 mb-10">
                    By proceeding, you confirm acceptance of this disclaimer and CLARA's Terms of Service and Privacy Policy.
                </p>
            </div>
        </div>
    );
}
